apiVersion: v1
kind: Service
metadata:
  
  labels:
    name: k8s-service
  name: k8s-service
  namespace: k8s  
spec:   
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    app: k8s 
  type: LoadBalancer